[package]
name = "static_hashmap"
version = "0.1.0"
authors = ["73fc <542591851@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.1.0"