[package]
name = "csv_challenge"
version = "0.1.0"
authors = ["73fc <542591851@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2"
structopt-derive = "0.2"